### ISSUE TITLE
Ошибка использования тега <p>

### ISSUE THREAD

**Issue by ac-amygdala** [TatyanaKharitonovich/SkillUp-lessons#1]
https://github.com/TatyanaKharitonovich/SkillUp-lessons/blob/c7dce3657aa77835966c41c8945c3354d92ac65d/homework_1%2C/index.html#L15-L16

Тег `<p>` нужен исключительно для одного параграфа текста.   
Любой блочный элемент или принудительный разрыв строки - автоматически завершает этот тег. Другими словами, использование любых тегов, кроме строчных, внутри тега `p` запрещено.

В данной ситуации либо `p` заменить на `div`, либо вообще отказаться от него. Судя по верстке - вокруг весь элемент каталога уже находится внутри отдельного `div`, и вот это решение правильное

**Comment by ac-amygdala** [comment]
Соответственно поправить нужно в каждом элементе каталога

**Comment by TatyanaKharitonovich** [comment]
Исправлено в коммите 17da4ec.
